// src/cars/routes/car.router.ts
import { Router } from "express";
import auth from "../../middlewares/auth-middleware";
import CarCtrl from "../controllers/car.controller";
import { ah } from "../../core/async-handler";
import { validate } from "../../middlewares/validate";
import { carDto, carId, carListQuery } from "../../validators/car.validators";
import Car from "../models/Car";
const r = Router();

// create
r.post("/", auth, carDto, validate, ah(CarCtrl.create));
r.post("/post-multi", auth, async (req, res) => {
  const userId = (req as any).user._id;

  const cars = [
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb001", // Toyota
      series: "665b11aa7f9f63d4fcabb011", // Camry
      generation: "665b11aa7f9f63d4fcabb021",
      year: 2020,
      mileage: 30000,
      price: 11500000,
      currency: "KZT",
      engine: { volume: 2.5, type: "petrol" },
      gearbox: "automatic",
      drive: "fwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Алматы",
      title: "Toyota Camry 2020",
      description: "Один владелец, отличное состояние.",
      features: ["ABS", "ESP", "Камера", "Круиз-контроль"],
      photos: ["https://cdn.example.com/camry2020.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb002", // BMW
      series: "665b11aa7f9f63d4fcabb012", // 5 Series
      generation: "665b11aa7f9f63d4fcabb022",
      year: 2019,
      mileage: 42000,
      price: 18500000,
      currency: "KZT",
      engine: { volume: 2.0, type: "diesel" },
      gearbox: "automatic",
      drive: "rwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Астана",
      title: "BMW 520d G30",
      description: "Пробег родной. Машина в отличном состоянии.",
      features: ["Кожа", "Панорама", "LED"],
      photos: ["https://cdn.example.com/bmw520d.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb003", // Mercedes
      series: "665b11aa7f9f63d4fcabb013", // E-Class
      generation: "665b11aa7f9f63d4fcabb023",
      year: 2018,
      mileage: 60000,
      price: 19500000,
      currency: "KZT",
      engine: { volume: 2.0, type: "petrol" },
      gearbox: "automatic",
      drive: "rwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Шымкент",
      title: "Mercedes E200 W213",
      description: "Дилерская, чистый салон.",
      features: ["ESP", "Камера 360", "Дистроник"],
      photos: ["https://cdn.example.com/e200.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb004", // Hyundai
      series: "665b11aa7f9f63d4fcabb014", // Tucson
      generation: "665b11aa7f9f63d4fcabb024",
      year: 2021,
      mileage: 22000,
      price: 12500000,
      currency: "KZT",
      engine: { volume: 2.0, type: "petrol" },
      gearbox: "automatic",
      drive: "awd",
      steeringSide: "left",
      customsCleared: true,
      city: "Караганда",
      title: "Hyundai Tucson 2021",
      description: "Как новая, полный привод.",
      features: ["Климат-контроль", "Круиз", "LED"],
      photos: ["https://cdn.example.com/tucson2021.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb005", // Kia
      series: "665b11aa7f9f63d4fcabb015", // Sportage
      generation: "665b11aa7f9f63d4fcabb025",
      year: 2021,
      mileage: 28000,
      price: 10800000,
      currency: "KZT",
      engine: { volume: 2.0, type: "petrol" },
      gearbox: "automatic",
      drive: "awd",
      steeringSide: "left",
      customsCleared: true,
      city: "Тараз",
      title: "Kia Sportage 2021",
      description: "Полный привод, климат, камера.",
      features: ["ESP", "ABS", "LED"],
      photos: ["https://cdn.example.com/sportage.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb001", // Toyota
      series: "665b11aa7f9f63d4fcabb011",
      generation: "665b11aa7f9f63d4fcabb021",
      year: 2020,
      mileage: 30000,
      price: 11500000,
      currency: "KZT",
      engine: { volume: 2.5, type: "petrol" },
      gearbox: "automatic",
      drive: "fwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Алматы",
      title: "Toyota Camry 2020",
      description: "Один владелец, отличное состояние.",
      features: ["ABS", "ESP", "Камера", "Круиз-контроль"],
      photos: ["https://cdn.example.com/camry2020.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb002", // BMW
      series: "665b11aa7f9f63d4fcabb012",
      generation: "665b11aa7f9f63d4fcabb022",
      year: 2019,
      mileage: 42000,
      price: 18500000,
      currency: "KZT",
      engine: { volume: 2.0, type: "diesel" },
      gearbox: "automatic",
      drive: "rwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Астана",
      title: "BMW 520d G30",
      description: "Пробег родной. Машина в отличном состоянии.",
      features: ["Кожа", "Панорама", "LED"],
      photos: ["https://cdn.example.com/bmw520d.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb003", // Mercedes
      series: "665b11aa7f9f63d4fcabb013",
      generation: "665b11aa7f9f63d4fcabb023",
      year: 2018,
      mileage: 60000,
      price: 19500000,
      currency: "KZT",
      engine: { volume: 2.0, type: "petrol" },
      gearbox: "automatic",
      drive: "rwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Шымкент",
      title: "Mercedes E200 W213",
      description: "Дилерская, чистый салон.",
      features: ["ESP", "Камера 360", "Дистроник"],
      photos: ["https://cdn.example.com/e200.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb004", // Hyundai
      series: "665b11aa7f9f63d4fcabb014",
      generation: "665b11aa7f9f63d4fcabb024",
      year: 2021,
      mileage: 22000,
      price: 12500000,
      currency: "KZT",
      engine: { volume: 2.0, type: "petrol" },
      gearbox: "automatic",
      drive: "awd",
      steeringSide: "left",
      customsCleared: true,
      city: "Караганда",
      title: "Hyundai Tucson 2021",
      description: "Как новая, полный привод.",
      features: ["Климат-контроль", "Круиз", "LED"],
      photos: ["https://cdn.example.com/tucson2021.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb005", // Kia
      series: "665b11aa7f9f63d4fcabb015",
      generation: "665b11aa7f9f63d4fcabb025",
      year: 2021,
      mileage: 28000,
      price: 10800000,
      currency: "KZT",
      engine: { volume: 2.0, type: "petrol" },
      gearbox: "automatic",
      drive: "awd",
      steeringSide: "left",
      customsCleared: true,
      city: "Тараз",
      title: "Kia Sportage 2021",
      description: "Полный привод, климат, камера.",
      features: ["ESP", "ABS", "LED"],
      photos: ["https://cdn.example.com/sportage.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb006",
      series: "665b11aa7f9f63d4fcabb016",
      generation: "665b11aa7f9f63d4fcabb026",
      year: 2022,
      mileage: 17000,
      price: 15800000,
      currency: "KZT",
      engine: { volume: 1.6, type: "hybrid" },
      gearbox: "cvt",
      drive: "fwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Алматы",
      title: "Toyota Corolla Hybrid",
      description: "Низкий расход топлива, без ДТП.",
      features: ["Круиз", "Камера", "ESP"],
      photos: ["https://cdn.example.com/corolla.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb007",
      series: "665b11aa7f9f63d4fcabb017",
      generation: "665b11aa7f9f63d4fcabb027",
      year: 2021,
      mileage: 19000,
      price: 21000000,
      currency: "KZT",
      engine: { volume: 3.5, type: "petrol" },
      gearbox: "automatic",
      drive: "awd",
      steeringSide: "left",
      customsCleared: true,
      city: "Астана",
      title: "Lexus RX 350",
      description: "Официальная, без повреждений.",
      features: ["Панорама", "Кожа", "Навигация"],
      photos: ["https://cdn.example.com/lexusrx350.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb008",
      series: "665b11aa7f9f63d4fcabb018",
      generation: "665b11aa7f9f63d4fcabb028",
      year: 2022,
      mileage: 10000,
      price: 17500000,
      currency: "KZT",
      engine: { volume: 2.5, type: "diesel" },
      gearbox: "automatic",
      drive: "awd",
      steeringSide: "left",
      customsCleared: true,
      city: "Актобе",
      title: "Mazda CX-5",
      description: "Практически новая, не требует вложений.",
      features: ["ABS", "ESP", "Камера"],
      photos: ["https://cdn.example.com/cx5.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb009",
      series: "665b11aa7f9f63d4fcabb019",
      generation: "665b11aa7f9f63d4fcabb029",
      year: 2020,
      mileage: 31000,
      price: 16000000,
      currency: "KZT",
      engine: { volume: 2.0, type: "petrol" },
      gearbox: "automatic",
      drive: "awd",
      steeringSide: "left",
      customsCleared: true,
      city: "Усть-Каменогорск",
      title: "Honda CR-V",
      description: "Надёжный кроссовер в идеальном состоянии.",
      features: ["Кожа", "ESP", "Камера"],
      photos: ["https://cdn.example.com/crv.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb010",
      series: "665b11aa7f9f63d4fcabb020",
      generation: "665b11aa7f9f63d4fcabb030",
      year: 2023,
      mileage: 5000,
      price: 32000000,
      currency: "KZT",
      engine: { volume: 0, type: "ev" },
      gearbox: "automatic",
      drive: "rwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Алматы",
      title: "Tesla Model 3",
      description: "Электро, топовая комплектация.",
      features: ["Автопилот", "Панорама", "LED"],
      photos: ["https://cdn.example.com/tesla.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb001",
      series: "665b11aa7f9f63d4fcabb011",
      generation: "665b11aa7f9f63d4fcabb021",
      year: 2020,
      mileage: 30000,
      price: 11500000,
      currency: "KZT",
      engine: { volume: 2.5, type: "petrol" },
      gearbox: "automatic",
      drive: "fwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Алматы",
      title: "Toyota Camry 2020",
      description: "Один владелец, отличное состояние.",
      features: ["ABS", "ESP", "Камера", "Круиз-контроль"],
      photos: ["https://cdn.example.com/camry2020.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb002",
      series: "665b11aa7f9f63d4fcabb012",
      generation: "665b11aa7f9f63d4fcabb022",
      year: 2019,
      mileage: 42000,
      price: 18500000,
      currency: "KZT",
      engine: { volume: 2.0, type: "diesel" },
      gearbox: "automatic",
      drive: "rwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Астана",
      title: "BMW 520d G30",
      description: "Пробег родной. Машина в отличном состоянии.",
      features: ["Кожа", "Панорама", "LED"],
      photos: ["https://cdn.example.com/bmw520d.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb003",
      series: "665b11aa7f9f63d4fcabb013",
      generation: "665b11aa7f9f63d4fcabb023",
      year: 2018,
      mileage: 60000,
      price: 19500000,
      currency: "KZT",
      engine: { volume: 2.0, type: "petrol" },
      gearbox: "automatic",
      drive: "rwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Шымкент",
      title: "Mercedes E200 W213",
      description: "Дилерская, чистый салон.",
      features: ["ESP", "Камера 360", "Дистроник"],
      photos: ["https://cdn.example.com/e200.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb004",
      series: "665b11aa7f9f63d4fcabb014",
      generation: "665b11aa7f9f63d4fcabb024",
      year: 2021,
      mileage: 22000,
      price: 12500000,
      currency: "KZT",
      engine: { volume: 2.0, type: "petrol" },
      gearbox: "automatic",
      drive: "awd",
      steeringSide: "left",
      customsCleared: true,
      city: "Караганда",
      title: "Hyundai Tucson 2021",
      description: "Как новая, полный привод.",
      features: ["Климат-контроль", "Круиз", "LED"],
      photos: ["https://cdn.example.com/tucson2021.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb005",
      series: "665b11aa7f9f63d4fcabb015",
      generation: "665b11aa7f9f63d4fcabb025",
      year: 2021,
      mileage: 28000,
      price: 10800000,
      currency: "KZT",
      engine: { volume: 2.0, type: "petrol" },
      gearbox: "automatic",
      drive: "awd",
      steeringSide: "left",
      customsCleared: true,
      city: "Тараз",
      title: "Kia Sportage 2021",
      description: "Полный привод, климат, камера.",
      features: ["ESP", "ABS", "LED"],
      photos: ["https://cdn.example.com/sportage.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb006",
      series: "665b11aa7f9f63d4fcabb016",
      generation: "665b11aa7f9f63d4fcabb026",
      year: 2022,
      mileage: 17000,
      price: 15800000,
      currency: "KZT",
      engine: { volume: 1.6, type: "hybrid" },
      gearbox: "cvt",
      drive: "fwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Алматы",
      title: "Toyota Corolla Hybrid",
      description: "Низкий расход топлива, без ДТП.",
      features: ["Круиз", "Камера", "ESP"],
      photos: ["https://cdn.example.com/corolla.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb007",
      series: "665b11aa7f9f63d4fcabb017",
      generation: "665b11aa7f9f63d4fcabb027",
      year: 2021,
      mileage: 19000,
      price: 21000000,
      currency: "KZT",
      engine: { volume: 3.5, type: "petrol" },
      gearbox: "automatic",
      drive: "awd",
      steeringSide: "left",
      customsCleared: true,
      city: "Астана",
      title: "Lexus RX 350",
      description: "Официальная, без повреждений.",
      features: ["Панорама", "Кожа", "Навигация"],
      photos: ["https://cdn.example.com/lexusrx350.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb008",
      series: "665b11aa7f9f63d4fcabb018",
      generation: "665b11aa7f9f63d4fcabb028",
      year: 2022,
      mileage: 10000,
      price: 17500000,
      currency: "KZT",
      engine: { volume: 2.5, type: "diesel" },
      gearbox: "automatic",
      drive: "awd",
      steeringSide: "left",
      customsCleared: true,
      city: "Актобе",
      title: "Mazda CX-5",
      description: "Практически новая, не требует вложений.",
      features: ["ABS", "ESP", "Камера"],
      photos: ["https://cdn.example.com/cx5.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb009",
      series: "665b11aa7f9f63d4fcabb019",
      generation: "665b11aa7f9f63d4fcabb029",
      year: 2020,
      mileage: 31000,
      price: 16000000,
      currency: "KZT",
      engine: { volume: 2.0, type: "petrol" },
      gearbox: "automatic",
      drive: "awd",
      steeringSide: "left",
      customsCleared: true,
      city: "Усть-Каменогорск",
      title: "Honda CR-V",
      description: "Надёжный кроссовер в идеальном состоянии.",
      features: ["Кожа", "ESP", "Камера"],
      photos: ["https://cdn.example.com/crv.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb010",
      series: "665b11aa7f9f63d4fcabb020",
      generation: "665b11aa7f9f63d4fcabb030",
      year: 2023,
      mileage: 5000,
      price: 32000000,
      currency: "KZT",
      engine: { volume: 0, type: "ev" },
      gearbox: "automatic",
      drive: "rwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Алматы",
      title: "Tesla Model 3",
      description: "Электро, топовая комплектация.",
      features: ["Автопилот", "Панорама", "LED"],
      photos: ["https://cdn.example.com/tesla.jpg"],
    },
    // 10 more cars here ↓↓↓
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb031",
      series: "665b11aa7f9f63d4fcabb041",
      generation: "665b11aa7f9f63d4fcabb051",
      year: 2017,
      mileage: 45000,
      price: 9800000,
      currency: "KZT",
      engine: { volume: 1.4, type: "petrol" },
      gearbox: "manual",
      drive: "fwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Павлодар",
      title: "Volkswagen Polo",
      description: "Надёжный, экономичный, городской.",
      features: ["ESP", "Кондиционер", "Мультируль"],
      photos: ["https://cdn.example.com/polo.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb032",
      series: "665b11aa7f9f63d4fcabb042",
      generation: "665b11aa7f9f63d4fcabb052",
      year: 2022,
      mileage: 7000,
      price: 18500000,
      currency: "KZT",
      engine: { volume: 2.0, type: "petrol" },
      gearbox: "robot",
      drive: "fwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Костанай",
      title: "Audi A3 2022",
      description: "Премиум седан в идеальном состоянии.",
      features: ["LED", "Камера", "Парктроник"],
      photos: ["https://cdn.example.com/a3.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb033",
      series: "665b11aa7f9f63d4fcabb043",
      generation: "665b11aa7f9f63d4fcabb053",
      year: 2019,
      mileage: 38000,
      price: 9700000,
      currency: "KZT",
      engine: { volume: 1.8, type: "petrol" },
      gearbox: "cvt",
      drive: "fwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Семей",
      title: "Nissan Qashqai",
      description: "Отличный городской кроссовер.",
      features: ["Климат", "ESP", "LED"],
      photos: ["https://cdn.example.com/qashqai.jpg"],
    },
    {
      seller: userId,
      brand: "665b11aa7f9f63d4fcabb034",
      series: "665b11aa7f9f63d4fcabb044",
      generation: "665b11aa7f9f63d4fcabb054",
      year: 2020,
      mileage: 12000,
      price: 8900000,
      currency: "KZT",
      engine: { volume: 1.5, type: "petrol" },
      gearbox: "manual",
      drive: "fwd",
      steeringSide: "left",
      customsCleared: true,
      city: "Жезказган",
      title: "Lada Vesta",
      description: "Новая, на гарантии.",
      features: ["ABS", "ESP", "Кондиционер"],
      photos: ["https://cdn.example.com/vesta.jpg"],
    },
  ];

  try {
    const inserted = await Car.insertMany(cars);
    res
      .status(201)
      .json({ message: `${inserted.length} машин успешно добавлены.` });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: "Ошибка при сохранении машин в базу" });
  }
});

// list
r.get("/", carListQuery, validate, ah(CarCtrl.list));

// single
r.get("/:id", carId, validate, ah(CarCtrl.one));

// update / delete
r.patch("/:id", auth, carId, validate, ah(CarCtrl.update));
r.delete("/:id", auth, carId, validate, ah(CarCtrl.remove));

export default r;
